=== Niklan/niklan.net-content/blog/article.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Custom types -->
  <xs:simpleType name="articleIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9.-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="languageCodeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ru"/>
      <xs:enumeration value="en"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tagType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="softwareNameType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9/-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Root element -->
  <xs:element name="article">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="translations"/>
        <xs:element ref="compatibility" minOccurs="0"/>
        <xs:element ref="tags" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" type="articleIdType" use="required"/>
      <xs:attribute name="created" type="xs:dateTime" use="required"/>
      <xs:attribute name="updated" type="xs:dateTime" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Translations block -->
  <xs:element name="translations">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="translation" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="description" type="xs:string"/>
              <xs:element name="poster">
                <xs:complexType>
                  <xs:attribute name="src" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element ref="attachments" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="language" type="languageCodeType" use="required"/>
            <xs:attribute name="primary" type="xs:boolean"/>
            <xs:attribute name="src" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tags block -->
  <xs:element name="tags">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tag" type="tagType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Compatibility block -->
  <xs:element name="compatibility">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="software" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="softwareNameType" use="required"/>
            <xs:attribute name="constraint" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Attachments block -->
  <xs:element name="attachments">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="attachment" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="src" type="xs:string" use="required"/>
            <xs:attribute name="title" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Niklan/niklan.net-content/blog/2013/03/24/drupal-7-creating-catalog-with-taxonomy-views-and-panels/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-7-creating-catalog-with-taxonomy-views-and-panels"
  created="2013-03-24T22:41:27"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 7: Создание каталога с применением Taxonomy, Views и Panels</title>
      <description>Создайте удобный каталог товаров с помощью Drupal 7, используя Taxonomy, Views и Panels.</description>
      <poster src="./image/poster.ru.png"/>
      <attachments>
        <attachment src="./attachment/child_terms.txt"
          title="Представление: Дочерние термины"/>
        <attachment src="./attachment/catalog.txt"
          title="Представление: Каталог (главная страница)"/>
        <attachment src="./attachment/product.txt"
          title="Представление: Вывод продукции в каталоге"/>
        <attachment src="./attachment/panels_catalog.txt"
          title="Panels: Отображение подкатегорий и товаров"/>
      </attachments>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2018/01/19/drupal-8-authentication-api/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-authentication-api"
  created="2018-01-19T19:17:14"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Authentication API — создание Authentication Provider</title>
      <description>
        Узнайте, как создавать собственные сервисы аутентификации в Drupal 8.
        Научитесь добавлять новые способы авторизации, такие как авторизация
        через API ключ, автоматическая авторизация с определённых IP-адресов и
        другие.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2015/11/04/drupal-8-tour-api/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-tour-api"
  created="2015-11-04T12:05:27"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Tour API</title>
      <description>
        Drupal 8 Tour API позволяет создавать интерактивные туры по
        административным страницам, предоставляя редакторам наглядные обучающие
        подсказки.
      </description>
      <poster src="./image/poster.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2013/04/17/drupal-7-integrating-color-module-guide/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-7-integrating-color-module-guide"
  created="2013-04-17T14:45:40"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Интеграция color-модуля в тему Drupal 7: подробное руководство</title>
      <description>Добавьте в свою тему поддержку Color-модуля и легко меняйте цвета!</description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2017/04/16/install-and-configure-drupal-vm-on-ubuntu/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="install-and-configure-drupal-vm-on-ubuntu"
  created="2017-04-16T09:50:31"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Установка и настройка Drupal VM на Ubuntu</title>
      <description>
        Узнайте, как установить и настроить Drupal VM на Ubuntu для локальной
        разработки.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>linux</tag>
    <tag>ubuntu</tag>
    <tag>web-server</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2014/10/10/mappy-7.x-1.4-8.x-1.0-rc1/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="mappy-7.x-1.4-8.x-1.0-rc1"
  created="2014-10-10T19:02:30"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Mappy: 7.x-1.4 / 8.x-1.0-rc1</title>
      <description>Список изменений.</description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
    <tag>drupal-8</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2018/05/04/drupal-8-configuration-schema/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-configuration-schema"
  created="2018-05-04T17:57:03"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Configuration Schema</title>
      <description>
        Узнайте, как создавать схемы для конфигурационных файлов в Drupal 8.
      </description>
      <poster src="./image/poster.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2013/02/04/d7fb-taxonomy/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-7-for-beginners-taxonomy"
  created="2013-02-04T23:11:39"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 7 для начинающих: Таксономия</title>
      <description>Разбираемся со словарями.</description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
  </tags>
</article>
