=== Niklan/niklan.net-content/blog/article.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Custom types -->
  <xs:simpleType name="articleIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9.-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="languageCodeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ru"/>
      <xs:enumeration value="en"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tagType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="softwareNameType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9/-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Root element -->
  <xs:element name="article">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="translations"/>
        <xs:element ref="compatibility" minOccurs="0"/>
        <xs:element ref="tags" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" type="articleIdType" use="required"/>
      <xs:attribute name="created" type="xs:dateTime" use="required"/>
      <xs:attribute name="updated" type="xs:dateTime" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Translations block -->
  <xs:element name="translations">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="translation" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="description" type="xs:string"/>
              <xs:element name="poster">
                <xs:complexType>
                  <xs:attribute name="src" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element ref="attachments" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="language" type="languageCodeType" use="required"/>
            <xs:attribute name="primary" type="xs:boolean"/>
            <xs:attribute name="src" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tags block -->
  <xs:element name="tags">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tag" type="tagType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Compatibility block -->
  <xs:element name="compatibility">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="software" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="softwareNameType" use="required"/>
            <xs:attribute name="constraint" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Attachments block -->
  <xs:element name="attachments">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="attachment" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="src" type="xs:string" use="required"/>
            <xs:attribute name="title" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Niklan/niklan.net-content/blog/2016/04/04/drupal-7-how-to-theme-using-display-suite-and-field-group/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-7-how-to-theme-using-display-suite-and-field-group"
  created="2016-04-04T19:54:09"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>DS + FG proof of concept или как я верстаю в Drupal</title>
      <description>
        В этой статье я расскажу о своём подходе к вёрстке на Drupal, основанном
        на использовании связки DisplaySuite и FieldGroup. Я сравню его с
        другими методами и объясню, почему выбрал именно этот способ, а также
        опишу его преимущества и недостатки.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
    <tag>theming</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2020/05/29/drupal-8-9-sending-emails-using-oop-and-dependency-injection/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-9-sending-emails-using-oop-and-dependency-injection"
  created="2020-05-29T14:47:23"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8, 9: Отправка писем используя ООП и Dependency Injection</title>
      <description>
        Узнайте, как отправлять письма в Drupal 8 и 9 с использованием ООП и
        Dependency Injection для улучшения структуры кода и удобства разработки.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
    <tag>drupal-9</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2025/12/08/drupal-11-3/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-11-3-overview"
  created="2025-12-08T15:00:00"
  updated="2025-12-08T15:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 11.3: Обзор ключевых изменений</title>
      <description>
        В новый релиз вошли интеграция HTMX, модуль для Symfony Mailer, частичный перевод рендер-массивов на ООП,
        поддержка ООП-хуков в темах, YAML-экспорт содержимого, асинхронный драйвер MySQLi и многое другое.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2016/09/17/drupal-8-how-to-create-custom-plugin-type/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-how-to-create-custom-plugin-type"
  created="2016-09-17T13:39:21"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Plugin API — создание собственных типов плагинов</title>
      <description>
        Узнайте, как создавать собственные типы плагинов в Drupal 8. Это
        позволит вам расширить функциональность вашего сайта и добавить новые
        возможности.
      </description>
      <poster src="./image/poster.ru.png"/>
      <attachments>
        <attachment src="./attachment/custom_csv_import_article.csv"
          title="Заготовка для теста импорта статей"/>
        <attachment src="./attachment/custom_csv_import_page.csv"
          title="Заготовка для теста импорта страниц"/>
      </attachments>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2020/04/30/drupal-8-9-lock-and-lock-persistent/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-9-lock-and-lock-persistent"
  created="2020-04-30T14:13:22"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8, 9: lock и lock.persistent — блокировка состояния</title>
      <description>
        Drupal 8, 9: блокировка состояния — узнайте, как обеспечить целостность
        данных, предотвратить конфликты при работе с сайтом и избежать
        «состояние гонки».
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
    <tag>drupal-9</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2012/12/31/ubuntu-12-web-server/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="ubuntu-12-web-server"
  created="2012-12-31T22:39:23"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Установка веб-сервера на Ubuntu 12.x</title>
      <description>Подготавливаем локальный веб-сервер для разработки на Ubuntu 12.x.</description>
      <poster src="./image/poster.ru.png"/>
      <attachments>
        <attachment src="./attachment/add_alias.sh.zip" title="Скрипт добавления алиасов"/>
        <attachment src="./attachment/add_alias_indomain13-10.sh.zip" title="Скрипт добавления алиасов Ubuntu 13.10"/>
      </attachments>
    </translation>
  </translations>
  <tags>
    <tag>ubuntu</tag>
    <tag>linux</tag>
    <tag>web_server</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2017/07/26/drupal-8-how-to-create-a-custom-views-field-handler/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-how-to-create-a-custom-views-field-handler"
  created="2017-07-26T18:51:00"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8 Views Field Handler Plugin — собственные поля для Views</title>
      <description>
        Руководство по добавлению собственных полей в модуль Views.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
    <tag>performance</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2016/09/02/how-to-group-content-in-views/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="how-to-group-content-in-views"
  created="2016-09-02T08:06:03"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal - группировка материалов во Views</title>
      <description>
        Узнайте, как объединять элементы по определённому признаку для улучшения
        структуры и навигации вашего сайта.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
    <tag>drupal-8</tag>
  </tags>
</article>
