=== Niklan/niklan.net-content/blog/article.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Custom types -->
  <xs:simpleType name="articleIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9.-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="languageCodeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ru"/>
      <xs:enumeration value="en"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="tagType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="softwareNameType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-z0-9/-]+"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Root element -->
  <xs:element name="article">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="translations"/>
        <xs:element ref="compatibility" minOccurs="0"/>
        <xs:element ref="tags" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" type="articleIdType" use="required"/>
      <xs:attribute name="created" type="xs:dateTime" use="required"/>
      <xs:attribute name="updated" type="xs:dateTime" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Translations block -->
  <xs:element name="translations">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="translation" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="description" type="xs:string"/>
              <xs:element name="poster">
                <xs:complexType>
                  <xs:attribute name="src" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element ref="attachments" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="language" type="languageCodeType" use="required"/>
            <xs:attribute name="primary" type="xs:boolean"/>
            <xs:attribute name="src" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Tags block -->
  <xs:element name="tags">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tag" type="tagType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Compatibility block -->
  <xs:element name="compatibility">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="software" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="softwareNameType" use="required"/>
            <xs:attribute name="constraint" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Attachments block -->
  <xs:element name="attachments">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="attachment" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="src" type="xs:string" use="required"/>
            <xs:attribute name="title" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Niklan/niklan.net-content/blog/2013/12/16/indexisto-drupal-7-module/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="indexisto-drupal-7-module"
  created="2013-12-16T17:30:40"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Indexisto - поиск для Drupal</title>
      <description>Интеграция Indexisto с Drupal.</description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
    <tag>search</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2018/06/29/two-ways-of-installing-drupal-8/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="two-ways-of-installing-drupal-8"
  created="2018-06-29T17:11:50"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Два варианта установки ядра</title>
      <description>
        Узнайте, как установить ядро Drupal 8 двумя способами: стандартным с
        drupal.org и через Composer Drupal Project. Сравните плюсы и минусы
        каждого метода, а также научитесь мигрировать между ними.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2019/04/19/drupal-8-access-check/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-access-check"
  created="2019-04-19T20:29:18"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Сервис access_check — гибкая и переиспользуемая проверка прав доступа к маршрутам</title>
      <description>
        Сервис access_check — это гибкий и переиспользуемый инструмент для
        проверки прав доступа к маршрутам. Он позволяет настраивать сложные
        правила доступа, делая ваш сайт более безопасным.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
    <tag>access</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2017/07/04/drupal-8-language-negotiation/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-language-negotiation"
  created="2017-07-04T17:39:09"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: LanguageNegotiaton — программное определение языка</title>
      <description>
        В этом материале рассмотрим, как добавить на сайт возможность
        программного определения языка с помощью плагина LanguageNegotiator.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
    <tag>i18n</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2013/02/14/drupal-7-for-beginners-modules/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-7-for-beginners-modules"
  created="2013-02-14T12:00:30"
  updated="2025-07-17T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 7 для начинающих: Модули</title>
      <description>Разбираемся с модулями в Drupal 7.</description>
      <poster src="./image/poster.ru.png"/>
      <attachments>
        <attachment src="./attachment/dfbeginners.tar.gz"
          title="Результат выполнения"/>
      </attachments>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2013/04/20/drupal-7-views-grid-formatting-with-divs/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-7-views-grid-formatting-with-divs"
  created="2013-04-20T18:32:13"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Форматирование вывода Views в виде сетки на Drupal 7 с использованием div-элементов</title>
      <description>Узнайте, как использовать div-элементы для вывода сетки Views и обеспечения адаптивности дизайна.</description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-7</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2018/04/26/drupal-8-creating-extra-fields/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-creating-extra-fields"
  created="2018-04-26T21:00:14"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Создание псевдо-полей (Extra Fields)</title>
      <description>
        Создаём псевдо-поля в Drupal 8: узнайте, как добавить новые поля к
        существующим сущностям и формам.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
  </tags>
</article>

=== Niklan/niklan.net-content/blog/2019/05/02/drupal-8-user-data-service/article.xml
<?xml version="1.0" encoding="UTF-8"?>
<article xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../../../article.xsd"
  id="drupal-8-user-data-service"
  created="2019-05-02T19:44:51"
  updated="2024-11-30T00:00:00">
  <translations>
    <translation language="ru" primary="true" src="./article.ru.md">
      <title>Drupal 8: Сервис user.data — хранилище данных пользователей</title>
      <description>
        Сервис user.data — это инструмент, который позволяет хранить
        пользовательские данные в виде пар «ключ-значение». Это удобно для
        хранения дополнительной информации о пользователе, такой как
        предпочтения или настройки.
      </description>
      <poster src="./image/poster.ru.png"/>
    </translation>
  </translations>
  <tags>
    <tag>drupal</tag>
    <tag>drupal-8</tag>
  </tags>
</article>
